### ISSUE TITLE
continous-deployment

### ISSUE THREAD

**Issue by leventenyiro** [leventenyiro/poll#9]
```yaml
name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set JWT Secret
        id: set_jwt_secret
        run: |
          echo "Generating JWT secret key..."
          JWT_SECRET=$(node -e "require('crypto').randomBytes(16).toString('hex')")
          echo "JWT_SECRET=$JWT_SECRET" >> $GITHUB_ENV
          echo "JWT_SECRET generated"

      - name: Display JWT Secret
        run: |
          echo "JWT_SECRET=${{ env.JWT_SECRET }}"

      - name: Deploy Application
        # Add your deployment steps here
        run: |
          echo "Deploying the application..."
```
